# Generated by Django 4.1.1 on 2022-09-19 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apuntes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CategoriasApuntes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('apunte', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apuntes.apunte')),
                ('categoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apuntes.categoria')),
            ],
        ),
    ]
