# Generated by Django 4.1.1 on 2022-09-19 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apuntes', '0003_alter_categoriasapuntes_apunte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apunte',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
